### ISSUE TITLE
button with left label

### ISSUE THREAD

**Issue by edades** [dwalker39/DWBubbleMenuButton#3]
hi, have you any idea for put an label together the button.. for example 

-(HOME BUTTON)-
user(label) (BUTTON 1)
options(label) (BUTTON 2)

thanks :)

**Comment by dwalker39** [comment]
If I'm understanding correctly, you can either make a custom button where you handle creating the label yourself or you can set the title of a regular UIButton if that works for you. Maybe you should elaborate a bit on what your looking for if that wasn't it

**Comment by edades** [comment]
Sorry for my english, i need custom the menu like this image. 
![screenshot_2015-03-28-14-52-04](https://cloud.githubusercontent.com/assets/401513/6882124/576d53d6-d55a-11e4-9fc6-a1089fd96656.png)

Thanks for you time.

**Comment by dwalker39** [comment]
What you can do is, instead of passing a UIButton to DWBubbleMenuButton, you can instead create a custom button class that handles showing the label you want.

 I would go with a UIView with tap gesture added, inside it add a UILabel with your UIButton or just a UIIImageView with the image you'd like and you can layout views properly in that class. 

I might also add an option for passing UIViews and handle adding the tap gesture on the BubbleMenu side when I find the time.
